// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Locktera API Documentation',
  tagline: 'Comprehensive API documentation for Locktera',
  favicon: 'img/Favicon-Locktera.ico', // Updated to use Locktera favicon

  // Set the production URL of your site here
  url: 'https://share.locktera.com', // Change this to your deployment URL
  baseUrl: '/',

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'Locktera', // Change this to your GitHub org/user name
  projectName: 'Locktera-API-Documentation', // Change this to the repository name

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      }),
    ],
  ],

  themeConfig:
  /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
      ({
        navbar: {
          title: 'Locktera API',
          logo: {
            alt: 'Locktera Logo',
            src: 'img/Locktera-Logo-01.png', // Updated to use Locktera logo
          },
          items: [
            {
              type: 'doc',
              docId: 'intro',
              position: 'left',
              label: 'Documentation',
            },
            {
              to: '/ApiReference', // Link to the API reference generated by redocusaurus
              label: 'API Reference',
              position: 'left',
            },
            {
              href: 'https://github.com/Locktera', // Replace with your GitHub repo URL
              label: 'GitHub',
              position: 'right',
            },
          ],
        },
        footer: {
          style: 'dark',
          links: [
            {
              title: 'Docs',
              items: [
                {
                  label: 'API Documentation',
                  to: '/docs/intro',
                },
              ],
            },
            {
              title: 'Community',
              items: [
                {
                  label: 'GitHub',
                  href: 'https://github.com/Locktera', // Replace with your GitHub repo URL
                },
              ],
            },
          ],
          copyright: `Copyright © ${new Date().getFullYear()} Locktera. Built with Docusaurus.`,
        },
        prism: {
          theme: lightCodeTheme,
          darkTheme: darkCodeTheme,
        },
        redocusaurus: {
          specs: [
            {
              spec: '/openapi-spec.yml', // Path to your OpenAPI spec in the static folder
              route: '/api',             // Route where it will be displayed
            },
          ],
          theme: {
            primaryColor: '#2B5592', // Locktera branding color
          },
        },
      }),
};

module.exports = config;
